---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: web-app
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        location /api {
            proxy_pass http://api-service:8080;
        }
    }
  app.properties: |
    database.host=database
    database.port=5432
    database.name=myapp
    log.level=info
    cache.enabled=true