---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  labels:
    app: web-app
spec:
  template:
    spec:
      containers:
      - name: migration
        image: migrate/migrate:latest
        command:
        - migrate
        - -path
        - /migrations
        - -database
        - postgres://postgres:password@database:5432/myapp?sslmode=disable
        - up
        volumeMounts:
        - name: migrations
          mountPath: /migrations
      volumes:
      - name: migrations
        configMap:
          name: migration-scripts
      restartPolicy: Never
  backoffLimit: 3