---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage
  labels:
    app: web-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd